# Используем официальный Python 3.11
FROM python:3.11-slim

# Создаем рабочую директорию
WORKDIR /app

# Копируем проект
COPY . /app

# Обновляем pip и устанавливаем зависимости
RUN python -m pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

# Переменная окружения BOT_TOKEN
ENV BOT_TOKEN=${BOT_TOKEN}

# Запуск бота
CMD ["python", "bot.py"]
